### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by sushilraje**
# Type of change? 

- [ ] Bug fix
- [ ] New feature
- [ ] Enhancement
- [ ] Breaking change (breaks backward compatibility)

# Description, Context, Motivation 

...

**Checklist:**

- [ ] All tests passed
- [ ] The code follows the code style and conventions of this project
- [ ] The change requires a change to the documentation
- [ ] I have updated the documentation accordingly

---
This change is [Reviewable](https://reviewable.io/reviews/azure/pcs-remote-monitoring-webui/1121)

### CODE REVIEW

**Comment by ppathan** [comment]
Does this change only require package-lock.json change? Should there also be a package.json change?

**Comment by isaac73** [comment]
@ppathan - can we just merge this now so that we are not blocking other PRs?

**Comment by ppathan** [comment]
@isaac73 How is this blocking other PRs? I at least need to know what the plane for package.json is before we merge this in.

**Comment by isaac73** [comment]
https://github.com/Azure/pcs-remote-monitoring-webui/pull/1127 - is unable to build because of this issue.

@sushilraje can you please create an issue from build website?

**Comment by sushilraje** [comment]
If the npm audit didn't change the major version of the module then it will lock the minor version in package-lock.json

**Pull request merged**
