### PR TITLE
Fix string to boolean conversion

### PR DESCRIPTION
**Pull request by tiagoshibata**
# Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [X] The code follows the code style and conventions of this project.
- [ ] The change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

# Description of the change
Comparing `value.toLowerCase() === 'Y'` was clearly broken.

### CODE REVIEW

**Comment by ppathan** [comment]
Closed the PR since this has been stale and sitting for sometime after being approved. If you need to reopen, please do so.

**Comment by tiagoshibata** [comment]
Why was this closed instead of merged? It's a simple and clear bugfix which had been already approved, it is "stale" because I am waiting for it to be merged. I don't have anything to add from my side.

**Comment by ppathan** [comment]
This change has already been merged into master, but through a different PR.

**Comment by ppathan** [comment]
Can you please reopen a new PR, we recently made our repo public and can no longer update the branch that came from your fork. Since it is one line fix, we can do it as well. What do you want to do?

**Comment by tiagoshibata** [comment]
Reopened,

**Pull request closed without merging**
