### PR TITLE
Add tags to embed snippets in docs

### PR DESCRIPTION
**Pull request by dominicbetts**
Adding tags to enable embedding of snippets from walkthrough content in articles in docs.microsoft.com.

@asdonald - these tags need to be added before I can add the related articles to docs.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/pcs-remote-monitoring-webui/1123)

### CODE REVIEW

**Comment by dominicbetts** [comment]
@isaac73 - The PR shows **Azure:master** because the PR is coming from a branch in my fork of the repo **dominicbetts:add-doc-tags**. The changes are going to the **master** branch in your repo. The **Azure** just indicates that the repo is in the Azure GitHub organization.

**Comment by asdonald** [comment]
@Dominic Betts<mailto:dobett@microsoft.com>

The Travis is not able to build this branch because it can’t find it. From your PR I went to code, branches, active branches and I don’t see it in here:

I’m assuming that this is why it’s unable to merge.

[cid:image001.png@01D45FCE.28492150]

Ashley Donaldson
Program Manager – Azure IoT

**Comment by isaac73** [comment]
@dominicbetts - I think our build agent is not able to find your branch. I'm also unable to find your branch `dominicbetts:add-doc-tags` in the `<>Code` tab here in Github. Can you please create a PR through Github Website?

This may not be related but I think `:` in the branch name is not a good idea. We generally use `\` instead.

**Comment by dominicbetts** [comment]
@isaac73 @asdonald - I don't have write permissions in this repo - that's why I was creating the PR from my fork of the repo. If you want me to create the PR from a branch in this repo, can you give me the appropriate permissions?

For reference, this PR was created from this branch in my fork: https://github.com/dominicbetts/pcs-remote-monitoring-webui/tree/add-doc-tags

The reason for the ":" in the branch name is due to the fact that the PR is coming from my fork - this is standard GitHub notation.

**Comment by isaac73** [comment]
@dominicbetts - Our repo is open source, so everyone must be able to create a PR. For the time being I'll create a different PR from your above mentioned branch.

**Comment by isaac73** [comment]
@dominicbetts and @asdonald - It's bug with our new build agent it's unable to find other repo branches. I have triggered a manual build to address this.

**Pull request merged**
